version: "3.8"

services:
  app:
    image: pythonbrad/tamnza
    ports:
      - 80:80
    environment:
      MYSQL_ROOT_HOST: mysql
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: tamnza
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    volumes:
      - tamnza-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: tamnza

volumes:
  tamnza-mysql-data:

