on:

  push:
  
  schedule:
    - cron: "*/5 * * * *"

name: CI

jobs:

  unittest:

    # Set any variables we need
    env:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: tamnza
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: secret
      PHPUNIT_CMD: php ./phpunit

    runs-on: ubuntu-latest

    container:
      image: php:8.1

    steps:

    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: ./.github/workflows/install_deps.sh

    - name: Start MySQL server
      run: ./.github/workflows/start_database.sh

    - name: Build the database
      run: ./.github/workflows/build_database.sh

    - name: Run Testsuite
      run: ./test.sh

    - name: Removing all the user input for the next step
      run: bash -c "mysql -D $MYSQL_DATABASE <<< 'DELETE FROM classroom_user;'"

    - name: Run Application Testsuite
      run: ./test2.sh
