on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

name: CI

jobs:

  unittest:

    # Set any variables we need
    env:
      MYSQL_ROOT_HOST: mysql
      MYSQL_DATABASE: tamnza
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: secret
      TAMNZA_HOST: 127.0.0.1:8080
      PHPUNIT_CMD: php ./phpunit

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: tamnza
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    container:
      image: php:8.1

    steps:

    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: |
        apt-get update -yq
        apt-get install -yq wget libonig-dev curl
        # Install PHP extensions
        docker-php-ext-install mbstring pdo_mysql
        wget -q -O phpunit https://phar.phpunit.de/phpunit-9.phar

    - name: Init database
      run : php ./tamnza/tamnza/initdb.php

    - name: Run backend test
      run: ./test.sh

    - name: Clean the database
      run: |
        php ./tamnza/tamnza/initdb.php

    - name: Run frontend test
      run: ./test2.sh
